[project]
name = "github-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.0",
    "fastapi[standard]>=0.115.6",
    "pyjwt>=2.10.1",
    "requests>=2.32.3",
]
